Add label to Kubernetes services if supplied in yelpsoa-config
Yelp/paasta pull request #2931
Opened 2020-10-02 14:14 UTC by davent

If a `prometheus_shard` option is specified in the yelpsoa-config file, set `yelp.com/paasta_prometheus_shard` and `paasta.yelp.com/config_prometheus_shard` labels to the provided shard.

This label will be used by the Prometheus Service Monitor for the given shard to discover and scrape the service.

2020-10-02 18:11 UTC, keymone requested changes

2020-10-02 18:11 UTC, keymone commented on paasta_tools/kubernetes_tools.py
> +                    "yelp.com/paasta_prometheus_shard"
drop this label, it's deprecated naming scheme

2020-10-02 18:11 UTC, keymone commented on paasta_tools/kubernetes_tools.py
> +                    "paasta.yelp.com/config_prometheus_shard"
rename to `paasta.yelp.com/prometheus_shard`

2020-10-05 09:17 UTC, keymone approved these changes

2020-10-07 12:29 UTC, Rob-Johnson approved these changes

2020-10-07 12:42 UTC, merged