[setup_istio_mesh] rate limit arg limits number of write calls to k8s per second
Yelp/paasta pull request #3201
Opened 2021-09-06 16:20 UTC by keymone

2021-09-07 13:12 UTC, Buffer0x7cd approved these changes

2021-09-08 11:47 UTC, keymone commented
@TheNavigat you may want to look at 5e7defc and b14fec5. i'm changing registration label names as they need to be limited in size.

2021-09-09 11:23 UTC, TheNavigat requested changes

2021-09-09 11:23 UTC, TheNavigat commented on paasta_tools/kubernetes_tools.py
> +    return limit_size_with_hash(f"regs.{PAASTA_ATTRIBUTE_PREFIX}{namespace}")
You should replace this with `return(f"regs.{PAASTA_ATTRIBUTE_PREFIX}{limit_size_with_hash(namespace)}")

The 63 character limit is on the suffix part of the label, not the entire length. The entire length can be up to 253 characters in total. Check https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set for that

2021-09-10 09:48 UTC, Rob-Johnson approved these changes

2021-09-10 09:59 UTC, merged