Fix inconsistent spark driver and executor image
Yelp/paasta pull request #3996
Opened 2024-12-17 17:50 UTC by chi-yelp

2025-01-08 15:10 UTC, nemacysts requested changes

2025-01-08 15:10 UTC, nemacysts commented on paasta_tools/tron_tools.py
> +            docker_img="$PAASTA_DOCKER_IMAGE",
this is only the image name - it doesn't include the rest of the url

looking at the test below, we'd go from `"--conf spark.kubernetes.container.image=docker-registry.com:400/my_service:paasta-123abcde "` to `"--conf spark.kubernetes.container.image=my_service:paasta-123abcde "` with this change

2025-01-08 15:11 UTC, nemacysts commented on paasta_tools/tron_tools.py
> +            docker_img="$PAASTA_DOCKER_IMAGE",
(we'll probably want to use `self.get_docker_registry()` to get the registry)

2025-01-09 11:26 UTC, chi-yelp commented on paasta_tools/tron_tools.py
> +            docker_img="$PAASTA_DOCKER_IMAGE",
Updated to add registry url here and in the tests, thanks for catching this!

2025-01-16 17:31 UTC, nemacysts approved these changes

2025-02-11 18:25 UTC, merged